// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYP4jpNN_Dmtyzix5TaObhA4dKeG-AUvI',
    appId: '1:44314688631:web:56dd1c20535adeeb5a1a72',
    messagingSenderId: '44314688631',
    projectId: 'app-gallinas-dfeea',
    authDomain: 'app-gallinas-dfeea.firebaseapp.com',
    storageBucket: 'app-gallinas-dfeea.appspot.com',
    measurementId: 'G-8634NW73Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBerd408KXzYxTMLYth8W4_q7LWBUyPPRQ',
    appId: '1:44314688631:android:30907cf37c3e9dd45a1a72',
    messagingSenderId: '44314688631',
    projectId: 'app-gallinas-dfeea',
    storageBucket: 'app-gallinas-dfeea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDarnI-l2IH6Fw_8NdmHJ5LdwTKoEX-_n8',
    appId: '1:44314688631:ios:71287e597334aac05a1a72',
    messagingSenderId: '44314688631',
    projectId: 'app-gallinas-dfeea',
    storageBucket: 'app-gallinas-dfeea.appspot.com',
    androidClientId: '44314688631-iq42485rbmdoc7tm9dibductrc37j319.apps.googleusercontent.com',
    iosClientId: '44314688631-0d49dr6iq753t9khvat0s8ev80dkj3o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gallinero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDarnI-l2IH6Fw_8NdmHJ5LdwTKoEX-_n8',
    appId: '1:44314688631:ios:71287e597334aac05a1a72',
    messagingSenderId: '44314688631',
    projectId: 'app-gallinas-dfeea',
    storageBucket: 'app-gallinas-dfeea.appspot.com',
    androidClientId: '44314688631-iq42485rbmdoc7tm9dibductrc37j319.apps.googleusercontent.com',
    iosClientId: '44314688631-0d49dr6iq753t9khvat0s8ev80dkj3o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gallinero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYP4jpNN_Dmtyzix5TaObhA4dKeG-AUvI',
    appId: '1:44314688631:web:fffe129526fc4f6e5a1a72',
    messagingSenderId: '44314688631',
    projectId: 'app-gallinas-dfeea',
    authDomain: 'app-gallinas-dfeea.firebaseapp.com',
    storageBucket: 'app-gallinas-dfeea.appspot.com',
    measurementId: 'G-JSFFQTT67G',
  );

}